### ISSUE TITLE
Cannot build using build.py

### ISSUE THREAD

**Issue by kongxiao0532** [NetSys/S6#1]
I was trying to build the code using build.py but an error came out.
```
\S6Builder> Generating source code
S6CodeGen> Build application tests
mkdir: cannot create directory ‘../gen_source/test’: No such file or directory
  Fail to generate ../gen_source/test folder
S6CodeGen> Stop s6_codegen_history.py
Error has occured running command: ['./script/s6_codegen', 'generate_all']
```
It seems like an issue with /script/s6_codegen

**Comment by shinae-woo** [comment]
Hi @kongxiao0532,
Thank you for reminding me this. You might already address the issue by generating a folder "S6/gen_source". I fixed them in the master branch.
