### ISSUE TITLE
src_generator/codegen.py python libclang argument type size == -2

### ISSUE THREAD

**Issue by omzmarlon** [NetSys/S6#2]
Hi, the smart people behind S6,

When I run the build.py (which then runs codegen.py I think), the "arg.type.get_size()" actually returns -2 for all the custom types from S6 (in the case below, it is SwRef<TCPFlow>), which fails the following assertion.

![image](https://user-images.githubusercontent.com/13238492/47412969-ec1cc080-d721-11e8-955c-2d3e39be2422.png)
![image](https://user-images.githubusercontent.com/13238492/47412999-fb037300-d721-11e8-8c31-c49338ddeacd.png)

Not sure how to fix this?

Thanks

**Comment by omzmarlon** [comment]
Problem resolved. 
Not sure how but I had to use an Ubuntu 16.04 machine with **strictly follow the order** of dependency installation in the ReadMe.

**Comment by JanonWang** [comment]
> Problem resolved.
> Not sure how but I had to use an Ubuntu 16.04 machine with **strictly follow the order** of dependency installation in the ReadMe.

hi, there, I meet the same problem, so how did you solve it? I use an Ubuntu 18.04 and installed all the 3rd-party libraries and all the basic utilities (python-clang-3.6 replaced with python-clang-3.9, libclang-3.6-dev replaced with libclang-3.9-dev)

**Comment by JanonWang** [comment]
![image](https://user-images.githubusercontent.com/15688830/48422479-b22b6100-e799-11e8-8272-98da45764097.png)

**Comment by omzmarlon** [comment]
Hi Janon,

Here is a link to the steps we figured out: https://github.com/knodir/S6/tree/dev/ac2
However, we did it on Ubuntu 16.04, and also we didn't replace python-clang or libclang with their 3.9 versions. I suspect that S6 is very sensitive to which versions of dependency you use
